title: currenjin's writes
description: 사색적 기록물
baseurl: "/writes"
url: "https://currenjin.github.io"

author: currenjin
email: hyun0524e@naver.com
github_username: currenjin

# 마크다운 설정
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 포스트 URL 형식
permalink: /:categories/:title/

# 카테고리 설정
category_colors:
  철학: "#3a623a"
  역사: "#446954"
  AI: "#5c8d64"
  에세이: "#6b9b52"
  회고: "#757575"

